/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author khoa
 */
import java.util.Random;

import UseCaseScenarios.controller;
import UseCaseScenarios.scenario;

public class InsulinGUI extends javax.swing.JFrame {

	/**
	 * Creates new form InsulinGUI
	 */
	private scenario s;
	private controller cc;
	private PatientMode p;

	public InsulinGUI(scenario ss) {
		initComponents();
		s = ss;
		cc = new controller(s);
		if (Insulin < 40) {
			if (Glucagon < 40) {
				if (Battery < 40) {
					jErrorMessage.setText("Insulin, Glucagon and Battery running low!");
				} else {
					jErrorMessage.setText("Insulin and Glucagon running low!");
				}
			} else {
				if (Battery < 40) {
					jErrorMessage.setText("Insulin and Battery running low!");
				} else {
					jErrorMessage.setText("Insulin running low!");
				}
			}

		} else {
			if (Glucagon < 40) {
				if (Battery < 40) {
					jErrorMessage.setText("Glucagon and Battery running low!");
				} else {
					jErrorMessage.setText("Glucagon running low!");
				}
			} else {
				if (Battery < 40) {
					jErrorMessage.setText("Battery running low!");
				} else {
					jErrorMessage.setText("Normal Specification");
				}
			}
		}

		System.out.println(Insulin);
		System.out.println(Glucagon);
		System.out.println(Battery);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jFrame1 = new javax.swing.JFrame();
		jBattery = new javax.swing.JProgressBar();
		jInsulinReservoir = new javax.swing.JProgressBar();
		jGlucagonReservoir = new javax.swing.JProgressBar();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jErrorMessage = new javax.swing.JLabel();

		javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
		jFrame1.getContentPane().setLayout(jFrame1Layout);
		jFrame1Layout.setHorizontalGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 400, Short.MAX_VALUE));
		jFrame1Layout.setVerticalGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 300, Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jBattery.setValue(Battery);
		jBattery.setName("battery"); // NOI18N
		jBattery.setOpaque(true);
		jBattery.setRequestFocusEnabled(false);
		jBattery.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				jBatteryStateChanged(evt);
			}
		});

		jInsulinReservoir.setBackground(new java.awt.Color(153, 153, 0));
		jInsulinReservoir.setValue(Insulin);
		jInsulinReservoir.setName("Insulin Reservoir"); // NOI18N
		jInsulinReservoir.setString("100%");
		jInsulinReservoir.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				jInsulinReservoirStateChanged(evt);
			}
		});

		jGlucagonReservoir.setValue(Glucagon);
		jGlucagonReservoir.setName("Glucagon Reservoir"); // NOI18N
		jGlucagonReservoir.setString("100%");

		jTextArea1.setColumns(20);
		jTextArea1.setRows(200);
		jScrollPane1.setViewportView(jTextArea1);

		jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jButton3.setText("Physician Mode");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jButton4.setText("Patient Mode");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel1.setText("Time");

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel2.setText("Insulin Reservoir");

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel3.setText("Glucagon Reservoir");

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel4.setText("Insulin/Glucagon Pumping Device");

		jErrorMessage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addGroup(layout
						.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jInsulinReservoir, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(34, 34, 34)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jGlucagonReservoir, javax.swing.GroupLayout.DEFAULT_SIZE, 157,
										Short.MAX_VALUE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jScrollPane1)))
						.addGroup(layout.createSequentialGroup()
								.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 428,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(44, 44, 44)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jBattery, javax.swing.GroupLayout.PREFERRED_SIZE, 117,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(layout.createSequentialGroup().addGap(20, 20, 20)
												.addComponent(jLabel1)))))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jBattery, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(
												jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE,
																75, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE,
																75, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(18, 18, 18)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jLabel3,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 29,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabel2,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 29,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addComponent(jScrollPane1))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jInsulinReservoir, javax.swing.GroupLayout.DEFAULT_SIZE, 31,
												Short.MAX_VALUE)
										.addComponent(jGlucagonReservoir, javax.swing.GroupLayout.DEFAULT_SIZE, 31,
												Short.MAX_VALUE)
										.addComponent(jErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addContainerGap()));

		jGlucagonReservoir.getAccessibleContext().setAccessibleName("");

		pack();
		setSize(622, 300);
		setResizable(false);
	}// </editor-fold>//GEN-END:initComponents

	public void setText(double count) {
		if (p != null) {
			p.setText(count);
		}
		if (s.getReading() > 120 && s.Hinjected() == false) {
			if (s.getAuto()) {
				jTextArea1.append(Double.toString(count) + " min: ");
				jTextArea1.append("insulin injected");
				jTextArea1.append("\n");
			} else {
				if (s.getInject()) {
					jTextArea1.append(Double.toString(count) + " min: ");
					jTextArea1.append("insulin injected");
					jTextArea1.append("\n");
				} else {
					jTextArea1.append(Double.toString(count) + " min: ");
					jTextArea1.append("need insulin injection");
					jTextArea1.append("\n");
				}
			}
		} else if (s.getReading() < 90 && s.Hinjected() == false) {
			if (s.getAuto()) {
				jTextArea1.append(Double.toString(count) + " min: ");
				jTextArea1.append("glucagon injected");
				jTextArea1.append("\n");

			} else {
				if (s.getInject()) {
					jTextArea1.append(Double.toString(count) + " min: ");
					jTextArea1.append("glucagon injected");
					jTextArea1.append("\n");

				} else {
					jTextArea1.append(Double.toString(count) + " min: ");
					jTextArea1.append("need glucagon injection");
					jTextArea1.append("\n");
				}
			}
		} else if (s.getSensorReading() == 0) {
			jTextArea1.append(Double.toString(count) + " min: ");
			jTextArea1.append("sensor fault");
			jTextArea1.append("\n");
		}
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		// TODO add your handling code here:
		new PhysicianMode(cc).setVisible(true);

	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		// TODO add your handling code here:
		p = new PatientMode(Insulin, Glucagon, Battery, cc);
		p.setVisible(true);
//		p.setText();
	}// GEN-LAST:event_jButton4ActionPerformed

	private void jInsulinReservoirStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_jInsulinReservoirStateChanged
		// TODO add your handling code here:
	}// GEN-LAST:event_jInsulinReservoirStateChanged

	private void jBatteryStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_jBatteryStateChanged
		// TODO add your handling code here:
	}// GEN-LAST:event_jBatteryStateChanged

	/**
	 * @param args
	 *            the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JProgressBar jBattery;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jErrorMessage;
	private javax.swing.JFrame jFrame1;
	private javax.swing.JProgressBar jGlucagonReservoir;
	private javax.swing.JProgressBar jInsulinReservoir;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	// End of variables declaration//GEN-END:variables
	Random rand = new Random();
	private int Insulin = rand.nextInt(99) + 1;
	private int Glucagon = rand.nextInt(99) + 1;
	private int Battery = rand.nextInt(99) + 1;
}
