/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import UseCaseScenarios.controller;
import UseCaseScenarios.scenario;

/**
 *
 * @author khoa
 */
public class PatientMode extends javax.swing.JFrame {

	/**
	 * Creates new form PatientMode
	 */
	private controller cc;

	public PatientMode(int ins, int glc, int btr, controller c) {
		Insulin = ins;
		Glucagon = glc;
		Battery = btr;
		cc = c;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jToggleButton1 = new javax.swing.JToggleButton();
		jInsulin = new javax.swing.JButton();
		jGlucagon = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jProgressBar2 = new javax.swing.JProgressBar();
		jProgressBar3 = new javax.swing.JProgressBar();
		jLabel4 = new javax.swing.JLabel();
		jBattery = new javax.swing.JProgressBar();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jLabel2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setPreferredSize(new java.awt.Dimension(622, 279));
		setSize(new java.awt.Dimension(622, 279));

		jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jToggleButton1.setText("Switch to Manual/Auto Mode");
		jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jToggleButton1ActionPerformed(evt);
			}
		});

		jInsulin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jInsulin.setText("Inject Insulin");
		jInsulin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				if (cc.getAuto()) {
					System.out.println("auto mode, action cannot perform");
				} else {
					cc.setInject(true);
				}
			}
		});

		jGlucagon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jGlucagon.setText("Inject Glucagon");
		jGlucagon.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				if (cc.getAuto()) {
					System.out.println("auto mode, action cannot perform");
				} else {
					cc.setInject(true);
				}
			}
		});

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel1.setText("Manual Mode Chosen");

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel3.setText("Insulin Reservoir");

		jProgressBar2.setBackground(new java.awt.Color(153, 153, 0));
		jProgressBar2.setValue(Glucagon);
		jProgressBar2.setName("Insulin Reservoir"); // NOI18N
		jProgressBar2.setString("100%");

		jProgressBar3.setBackground(new java.awt.Color(153, 153, 0));
		jProgressBar3.setValue(Insulin);
		jProgressBar3.setName("Insulin Reservoir"); // NOI18N
		jProgressBar3.setString("100%");

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel4.setText("Glucagon Reservoir");

		jBattery.setValue(Battery);

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel2.setText("jLabel2");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE,
														261, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGroup(layout.createSequentialGroup().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jInsulin, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(
														jProgressBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 185,
														Short.MAX_VALUE))
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup().addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.addComponent(jLabel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 192,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18, 18)
																.addComponent(jBattery,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 96,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(20, 20, 20))
														.addGroup(layout.createSequentialGroup().addGap(26, 26, 26)
																.addGroup(layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																				.addComponent(jLabel4,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(jGlucagon,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						179, Short.MAX_VALUE))
																		.addComponent(
																				jProgressBar2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				180,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addGroup(layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jScrollPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				202,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jLabel2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				196,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
																.addContainerGap()))))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jBattery, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jInsulin, javax.swing.GroupLayout.PREFERRED_SIZE, 99,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jGlucagon, javax.swing.GroupLayout.PREFERRED_SIZE, 99,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(
										jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jProgressBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 31,
														Short.MAX_VALUE)
												.addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 31,
														Short.MAX_VALUE)))
								.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addContainerGap()))));

		pack();
		setSize(622, 300);
		setResizable(false);
	}// </editor-fold>//GEN-END:initComponents

	private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton1ActionPerformed
		if (cc.getAutoPermission()) {
			cc.setAuto(!cc.getAuto());
			if (cc.getAuto() == true) {
				jLabel1.setText("Auto Mode Chosen");
			} else {
				jLabel1.setText("Manual Mode Chosen");
			}
		} else {
			System.out.println("cannot set mode");
		}

	}// GEN-LAST:event_jToggleButton1ActionPerformed

	public void setText(double count) {
		scenario s = cc.getScenario();
		String text = "current blood sugar: ";
		String b = Double.toString(s.getSensorReading());
		text = text.concat(b);
		if (s.getSensorReading() > 120 && !s.Hinjected()) {
			if (s.getAuto()) {
				jTextArea1.append(Double.toString(count) + " min: ");
				jTextArea1.append("insulin injected");
				jTextArea1.append("\n");
			} else {
				if (s.getInject()) {
					jTextArea1.append(Double.toString(count) + " min: ");
					jTextArea1.append("insulin injected");
					jTextArea1.append("\n");
				} else {
					jTextArea1.append(Double.toString(count) + " min: ");
					jTextArea1.append("need insulin injection");
					jTextArea1.append("\n");
				}
			}
		} else if (s.getSensorReading() < 90 && !s.Hinjected()) {
			if (s.getAuto()) {
				jTextArea1.append(Double.toString(count) + " min: ");
				jTextArea1.append("glucagon injected");
				jTextArea1.append("\n");

			} else {
				if (s.getInject()) {
					jTextArea1.append(Double.toString(count) + " min: ");
					jTextArea1.append("glucagon injected");
					jTextArea1.append("\n");

				} else {
					jTextArea1.append(Double.toString(count) + " min: ");
					jTextArea1.append("need glucagon injection");
					jTextArea1.append("\n");
				}
			}
		}
		jTextArea1.append(Double.toString(count) + " min: ");
		jTextArea1.append(text);
		jTextArea1.append("\n");
	}

	/**
	 * @param args
	 *            the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JProgressBar jBattery;
	private javax.swing.JButton jGlucagon;
	private javax.swing.JButton jInsulin;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JProgressBar jProgressBar2;
	private javax.swing.JProgressBar jProgressBar3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JToggleButton jToggleButton1;
	// End of variables declaration//GEN-END:variables
	private int Insulin;
	private int Glucagon;
	private int Battery;
}
